config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  post '/attend', to: 'events#attend'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  resources :events
  resources :users, only: [:index, :new, :create, :show]
  resources :event_attendees
  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true, length: { maximum: 250 }
  validates :location, presence: true
  validates :date, presence: true

  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :event_attendees, foreign_key: 'attended_event_id'
  has_many :attendees, through: 'event_attendees'
  scope :upcoming, -> { where('Date >= ?', Date.today).order('Date ASC') }
  scope :past, -> { where('Date <  ?', Date.today).order('Date DESC') }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
  validates :attendee_id, presence: true
  validates :attended_event_id, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 4 }
  has_many :events, foreign_key: 'creator_id'
  has_many :event_attendees, foreign_key: 'attendee_id'
  has_many :attended_events, through: 'event_attendees'

  def upcoming_events
    attended_events.upcoming
  end

  def past_events
    attended_events.past
  end

  def attending?(event)
    event.attendees.include?(self)
  end

  def attend!(event)
    event_attendees.create!(attended_event_id: event.id)
  end

  def cancel!(event)
    event_attendees.find_by(attended_event_id: event.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: %i[new create edit update destroy]

  def index
    @events_upcoming = Event.upcoming
    @events_past = Event.past
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:sucess] = 'Event Successfully created...'
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def attend
    attend = EventAttendee.create(attendee_id: params[:attend][:user_id], attended_event_id: params[:attend][:event_id])

    return redirect_to current_user if attend
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_name(params[:session][:name])
    if user
      log_in(user)
      redirect_to user, notice: 'Logged in!'
    else
      flash.now.alert = 'Name already Taken!'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'Please confirm your email address to continue'
      redirect_to @user
    else
      flash[:error] = 'Ooooppss, something went wrong!'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.upcoming_events
    @past_events = @user.past_events
    @past_created = @user.events.past
    @upcoming_created = @user.events.upcoming
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper

  private

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = 'Please log in.'
    redirect_to login_url
  end
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def attend_button
    if logged_in?
      if @event.attendees.to_a.none?(current_user)
        render 'attend_form'
      else
        content_tag(:p, 'You are already attending this event')
      end
    else
      content_tag(:p, 'You must log in or sign up to view the attendees')
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attend_form.html.erb
<% if logged_in? && current_user.attending?(@event) %> 
	<%= render 'cancel_form' %>
  <% else %>
	<%= form_with(url: attend_path, scope: :attend, local: true) do |f| %>
		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.hidden_field :event_id, value: params[:id] %>

		<%= f.submit "Attend", class: "btn waves-effect waves-light" %>
	<% end %>
<% end %>

app/views/events/_cancel_form.html.erb
<%= form_for(current_user.event_attendees.find_by(attended_event_id: @event.id),
	html: { method: :delete }) do |f| %>
	<%= f.submit "Cancel", class: "btn btn-sm btn-default" %>
<% end %>

app/views/events/_form.html.erb
<div class="row">
  <div class="col m6 offset-m3 center">
    <%= form_with(model: @event, local: true) do |f| %>
    <div class="inputfield"><%= f.label :title %>
    <%= f.text_field :title %> <br><br>
    </div>
    
    <div class="inputfield"><%= f.label :description %>
    <%= f.text_area :description, class: "validate" %><br><br>
    </div>
    
    <div class="inputfield"> <%= f.label :location %>
    <%= f.text_field :location, class: "validate" %><br><br>
    </div>
    

    <div class="inputfield"><%= f.label :date %>
    <%= f.text_field :date, class: "datepicker" %><br><br>
    </div>
    

    <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<h1>Events</h1>

  <div class="row">
    <h3>Past events</h3>
    <div class="col s12 m6">
    <% @events_past.each do |event| %>
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= link_to event.title, event %></span>
          <p><%= event.description %></p>
        </div>
        <div class="card-action">
          <p><%= event.creator.name %></p>
          <p><%= event.location %></p>
          <p><%= event.date %></p>
        </div>
      </div>
    <% end %>
    </div>
  </div>

<div class="row">
    <h3>Upcoming events</h3>
    <div class="col s12 m6">
    <% @events_upcoming.each do |event| %>
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= link_to event.title, event %></span>
          <p><%= event.description %></p>
        </div>
        <div class="card-action">
          <p><%= event.creator.name %></p>
          <p><%= event.location %></p>
          <p><%= event.date %></p>
        </div>
      </div>
    <% end %>
    </div>
  </div>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<div class="row">
    <div class="col s12 m6">
    <p>Created by: <%= @event.creator.name %></p>
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= link_to @event.title, @event %></span>
          <p><%= @event.description %></p>
        </div>
        <div class="card-action">
          <p><%= @event.location %></p>
          <p><%= @event.date %></p>
        </div>
      </div>
    </div>
</div>
<h4>Attendees</h4>
 <% @event.attendees.each do |attendee| %>
                <span class="attendee">
                    <%=link_to attendee.name, attendee %>
                </span> <br/>
 <% end %>
  <%= attend_button %>

<br>

<%= link_to '<< Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= render partial: 'shared/nav' %>
    <%= render partial: 'shared/message' %>
     <main class="lighten-4"> 
        <div class="container">
          <%= yield %>
        </div>
    
    </main>
    <script>$(document).ready(function(){
        $('.sidenav').sidenav();
        $(".dropdown-trigger").dropdown();
        $('.datepicker').datepicker({
          autoClose: true
        });
      });
      </script>
  </body>
</html>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      M.toast({html: '<%= value %>'})
    <% end %>
  </script>
<% end %>

app/views/shared/_nav.html.erb
<header>
     <ul id="dropdown1" class="dropdown-content">
      <li> <%= link_to 'Users', users_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Log out', logout_path, method: :delete %></li>
    </ul>

     <ul id="dropdown2" class="dropdown-content">
      <li> <%= link_to 'Users', users_path %></li>
      <li class="divider"></li>
      <li><%= link_to 'Log out', logout_path, method: :delete %></li>
    </ul>
    
    <nav class=" teal darken-4 z-depth-2">
      <div class="container">
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo">Private Events</a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
           <li> <%= link_to 'Events', events_path %></li>
           <li> <%= link_to 'Create Event', new_event_path %></li>
            <% if !logged_in? %>
              <li><%= link_to 'Sign Up', signup_path %></li>
              <li><%= link_to 'Sign In', login_path %></li>
            <% else %>
              <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
     <ul class="sidenav" id="mobile-demo">
     <li> <%= link_to 'Events', events_path %></li>
     <li> <%= link_to 'Create Event', new_event_path %></li>
     <% if !logged_in? %>
         <li><%= link_to 'Sign Up', signup_path %></li>
         <li><%= link_to 'Sign In', login_path %></li>
      <% else %>
         <li><a class="dropdown-trigger" href="#!" data-target="dropdown2"><%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
    <% end %>
    </ul>
  </header>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <ul class="collection">
    <li class="collection-item"><%= link_to user.name, user %> </li>
  </ul>
<% end %>

app/views/users/new.html.erb
<div class="row">
    <div class="col m6 offset-m3 center">
	<h1>Sign Up</h1>
		<%= form_for(@user) do |f| %>
			
			<div class="input-field">
				<%= f.label :name %><br />
				<%= f.text_field :name, class: 'validate' %>
			</div>

			<%= f.submit "Create my account", class: "btn btn-primary btn-block" %>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
<div class="col m6 offset-m3 center">
<h4><%= @user.name %></h4>

<h1>Created Events</h1>
<h2>Past Hosted Events</h2>
<div class="row">
  <div class="col s12 m6">
    <% @past_created.each do |event| %>
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= link_to event.title, event %></span>
          <p><%= event.description %></p>
        </div>
        <div class="card-action">
          <p><%= event.creator.name %></p>
          <p><%= event.location %></p>
          <p><%= event.date %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<h2>Upcoming Hosted Events</h2>
<div class="row">
  <div class="col s12 m6">
    <% @upcoming_created.each do |event| %>
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= link_to event.title, event %></span>
          <p><%= event.description %></p>
        </div>
        <div class="card-action">
          <p><%= event.creator.name %></p>
          <p><%= event.location %></p>
          <p><%= event.date %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<h1>Attended Events</h1>

<h2>Past Events Attended</h2>
<ul class="collection">
  <% @past_events.each do |event| %> 
    <li class="collection-item"><%= link_to event.title, event %>
 <% end %>
</ul>

<h2>Upcoming Events to Attend</h2>
<ul class="collection">
  <% @upcoming_events.each do |event| %>
    <li class="collection-item"><%= link_to event.title, event %></li>
  <% end %>
</ul>
</div>
</div>